### ISSUE TITLE
Update-QlikApp with -customProperties with = sign

### ISSUE THREAD

**Issue by levi-turner** [ahaydon/Qlik-Cli#103]
**Expected Behavior**: `Operations Monitor` is updated with a value of `Yes=No` for custom property `CPExample`.

**Actual Behavior**: `Operations Monitor` is updated with a value of `Yes` for custom property `CPExample`.

**Steps to replicate**:
```
Connect-Qlik
Invoke-QlikPost -path "/qrs/CustomPropertyDefinition" -body '{"name":"CPExample","valueType":"Text","choiceValues":["Yes","Yes=No"],"objectTypes":["App"]}'
Get-QlikApp -filter "name eq 'Operations Monitor'" | Update-QlikApp -customProperties "CPExample=Yes=No"
```

**Comment by ahaydon** [comment]
Are you using the latest code from master branch? This should have been resolved in PR #95.

**Comment by levi-turner** [comment]
I have the latest from PSGallery:
```
Get-InstalledModule -Name Qlik-Cli

Version              Name                                Repository           Description
-------              ----                                ----------           -----------
1.17.0               Qlik-Cli                            PSGallery            This module contains cmdlets to manage...
```

which looks to be the latest release on GitHub and PSGallery but is out of sync with the code changes made after. Got it.

**Comment by ahaydon** [comment]
I will release a new version to PSGallery soon as there are a few fixes since the last release.
