### ISSUE TITLE
-TrustAllCerts asks for input

### ISSUE THREAD

**Issue by itibook** [ahaydon/Qlik-Cli#115]
Hello, 

in the latest version, when using the -TrustAllCerts parameter I am getting a prompt with "Certificate:" which did not occure in version 1.16. 

I just upgraded this morning from 16 to 18 and noticed the error...

thanks in advance!

**Comment by itibook** [comment]
Issue seems to affect also version 1.17.0

**Comment by ahaydon** [comment]
This issue was fixed in 1.18.2.

If you specify the -Username parameter then Certificate will be required as the username can only be specified for certificate authentication.

**Comment by itibook** [comment]
ah got it! Thanks!
