### ISSUE TITLE
App import request body is missing quotes

### ISSUE THREAD

**Issue by naavis** [ahaydon/Qlik-Cli#117]
With Qlik-CLI 1.17.0 and Qlik Sense Enterprise February 2020, `Import-QlikApp` fails with HTTP 400 Bad Request.

Calling `Import-QlikApp -file "test.qvf" -name "TestApp"` sends an HTTP POST request with a body `test.qvf`, which is not valid JSON. Qlik Sense expects the body to be `"test.qvf"`, which is valid JSON.

Proving this is the case, calling ``Import-QlikApp -file "`"test.qvf`"" -name "TestApp"`` with the escaped extra quotes works fine.

Here you see the filename is passed to `Invoke-QlikPost` as a plain string: https://github.com/ahaydon/Qlik-Cli/blob/master/resources/app.ps1#L104

**Comment by ahaydon** [comment]
I just pushed a fix for this so the filename should be correctly quoted

**Comment by naavis** [comment]
Thank you! Importing seems to work in 1.19.0.
