### ISSUE TITLE
error on using a Export-QlikApp - ConvertFrom-Json : Impossible de lier l'argument au paramètre InputObject

### ISSUE THREAD

**Issue by manufv** [ahaydon/Qlik-Cli#118]
error on using a Export-QlikApp -id "f72031f6-b732-4763-b51d-c5055d98ba1a" -filename "efv1.qvf" -Verbose
COMMENTAIRES : filename=efv1.qvf
COMMENTAIRES : file=efv1.qvf
COMMENTAIRES : Raw output: 
COMMENTAIRES : Adding header x-Qlik-Xrfkey: kdlqpzuclbkulcgx
COMMENTAIRES : Calling Post for https://QLIK-SRV.infodata.lu/qrs/app/f72031f6-b732-4763-b51d-c5055d98ba1a/export/f5ab02a3-b371-4439-a1ea-d66803f3533a?xrfkey
=kdlqpzuclbkulcgx
COMMENTAIRES : POST https://qlik-srv.infodata.lu/qrs/app/f72031f6-b732-4763-b51d-c5055d98ba1a/export/f5ab02a3-b371-4439-a1ea-d66803f3533a?xrfkey=kdlqpzuclbk
ulcgx with -1-byte payload
COMMENTAIRES : received -1-byte response of content type application/json; charset=utf-8
COMMENTAIRES : Formatting response
COMMENTAIRES : Raw output: 
COMMENTAIRES : Adding header x-Qlik-Xrfkey: shxueyzaxulzgmek
COMMENTAIRES : Calling Get for https://QLIK-SRV.infodata.lu/tempcontent/36d6fb87-ec83-4a95-8604-7c8068d2cfaf/sx_cms%20-%20Contrat%20de%20maintenance.qvf?ser
verNodeId=5570b600-559c-4f6a-add1-189cac15cdf6&xrfkey=shxueyzaxulzgmek
COMMENTAIRES : GET https://qlik-srv.infodata.lu/tempcontent/36d6fb87-ec83-4a95-8604-7c8068d2cfaf/sx_cms - Contrat de maintenance.qvf?serverNodeId=5570b600-5
59c-4f6a-add1-189cac15cdf6&xrfkey=shxueyzaxulzgmek with 0-byte payload
COMMENTAIRES : received -1-byte response of content type application/vnd.qlik.sense.app
**ConvertFrom-Json : Impossible de lier l'argument au paramètre « InputObject », car il a la valeur Null.
Au caractère C:\Program Files\WindowsPowerShell\Modules\qlik-cli\1.18.2\functions\core.ps1:34 : 113
+ ... th @params -WebSession $script:webSession).Content | ConvertFrom-Json
+                                                          ~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidData : (:) [ConvertFrom-Json], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationErrorNullNotAllowed,Microsoft.PowerShell.Commands.ConvertFromJsonCommand**
 
COMMENTAIRES : Formatting response
COMMENTAIRES : Downloaded f72031f6-b732-4763-b51d-c5055d98ba1a to efv1.qvf

what can I do ?

**Comment by ahaydon** [comment]
This issue should be resolved in the latest code but has not yet been released to PowerShell Gallery, please can you test that it solves your problem and I will create a new release.

**Comment by manufv** [comment]
hello, thanks for your quick resopnse.
sorry but I don not understand, how do you want I install & test ? 
the last code ?

**Comment by ahaydon** [comment]
You can download the code from this GitHub repo, and load it into PowerShell using the command `Import-Module .\Qlik-Cli.psd1 -Force`. Then test the Export-QlikApp command again to see if it fixes the problem.

**Comment by manufv** [comment]
hello ahaydon, 
I confirm the current code solve the problem. 
the qapp is correctly exported and usable.
thank you very much.
