### ISSUE TITLE
Unable to find VirtualBox additions CD

### ISSUE THREAD

**Issue by gsbeaton** [ahaydon/Qlik-Cli#17]
Running the Packer script will throw an error and fails when the command tries to run the VBoxGuestAdditions.exe file of the virtual CD drive.  I'm not convinced this is needed if we are running the box headless though.

https://github.com/ahaydon/Qlik-Cli/blob/2b2f827ab0ea93731b27ca3c1c2f79370ece4848/packer/scripts/virtualbox-guest-tools.ps1#L14

**Comment by ahaydon** [comment]
the packer example will soon be removed from this repo, an alternative build can be found at https://github.com/clintcarr/PackerWin2k16.
