### ISSUE TITLE
Invoke-RestMethod : The remote name could not be resolved: 'sense-central'

### ISSUE THREAD

**Issue by chicrihemu** [ahaydon/Qlik-Cli#19]
Hi. I'm very new to Qlik-Cli. By follow your instruction, I got an error. Can you please help me to get it work?

Can you give me step by step how to use Export-QlikApp? 

Server Info:

1. Window Server 2016
2. Qlik Sense June 2017

![powershell_01](https://user-images.githubusercontent.com/31428114/29802731-c4e97670-8ca9-11e7-89cc-3c0798c4ce3b.jpg)
![powershell_02](https://user-images.githubusercontent.com/31428114/29802735-c8179f02-8ca9-11e7-8b38-11a75bbfd927.jpg)

**Comment by clintcarr** [comment]
What is the name that your Qlik Sense server resolves to? Is the hostname or an alias from DNS sense-central?

The error message you are getting appears to be a name resolution issue, or a connectivity issue.  Are you running this remotely?  Is port 4242 open on server?

**Comment by chicrihemu** [comment]
Hi @clintcarr . I'm running all server in VM. Firewall disable. My Qlik Sense server name is "QS" not "sense-central"...I'll change and try again.

Meanwhile, can you suggest how can I "Import and Publish" automatically?

`Import-QlikApp -file "C:\myQVF\Executive Dashboard.qvf" -name "Import Using PowerShell" -upload`

After imported QVF, QMC will generate app ID...ex. **f1810a95-66cc-4b37-9b3b-adc498abe14f** then I need to go to QMC or use command **Get-QlikApp** to get app ID and use with **Publish-QlikApp**

`Publish-QlikApp -id "f1810a95-66cc-4b37-9b3b-adc498abe14f" -stream "Executive" -name "Publish Using PowerShell"`

What I am looking for is publish app (no need to find app id) based on imported app name. Something like:
`Import-QlikApp -file "C:\myQVF\Executive Dashboard.qvf" -name "Import Using PowerShell" -upload`
`Publish-QlikApp -ImportedAppName "Import Using PowerShell" -stream "Executive" -name "Publish Using PowerShell"`

How to overcome this?

Thanks in advance.

**Comment by clintcarr** [comment]
Here is an example.
`
#Connect to Qlik Sense with default credentials
connect-qlik QS -useDefaultCredentials
#import an app
Import-QlikApp -name "New App" -file "c:\folder\folder\sales.qvf" -upload
#publish app to stream
Publish-QlikApp -id $(Get-QlikApp -filter "name eq 'New App'").id -stream $(Get-QlikStream -filter "name eq 'Everyone'").id -name "New App"
`

**Comment by chicrihemu** [comment]
@clintcarr Perfect...this tiny tool reduced number of CLICK a lots. Thank you :)
