### ISSUE TITLE
Unable to create one time trigger for a task

### ISSUE THREAD

**Issue by SQLJames** [ahaydon/Qlik-Cli#22]
I am working on creating a deployment script for our new versions of our app. 
Before we deploy the apps we like to reload them to ensure they have the latest data. 
Currently it seems that the only way to create a task is with a daily trigger. For my use case I would like to use the onetime trigger.

The below snippet is from Add-QlikTrigger
```

If($date) {
      $date = Get-Date -Format yyyy-MM-ddTHH:mm:ss.000Z $date
      $update = @{
        schemaEvents = @(@{
          name = "Daily";
          enabled = $true;
```

**Comment by ahaydon** [comment]
The task triggers still need some work to make them fully functional, for now I suggest using Invoke-QlikPost /qrs/app/{id}/reload to trigger a reload of an app. This is the same as reloading from the app list in QMC.

**Comment by SQLJames** [comment]
Got it, thank you for the heads up.
