### ISSUE TITLE
Start-QlikTask output status

### ISSUE THREAD

**Issue by theobondarec** [ahaydon/Qlik-Cli#221]
Hi,

is there a list of all the possible status in the System.Object returned by Start-QlikTask ?

Thanks a lot,

Theo

**Comment by countnazgul** [comment]
These?

```js
"values": [
    "0: NeverStarted",
    "1: Triggered",
    "2: Started",
    "3: Queued",
    "4: AbortInitiated",
    "5: Aborting",
    "6: Aborted",
    "7: FinishedSuccess",
    "8: FinishedFail",
    "9: Skipped",
    "10: Retry",
    "11: Error",
    "12: Reset",
    "13: DistributionQueue",
    "14: DistributionRunning"
]
```

btw all these can be retrieved from QRS [/qrs/about/api/enums](https://help.qlik.com/en-US/sense-developer/May2024/APIs/RepositoryServiceAPI/index.html?page=237) endpoint.

**Comment by theobondarec** [comment]
that's it !
thanks a lot, I couldn't find them
