### ISSUE TITLE
Reload-Task statuses times

### ISSUE THREAD

**Issue by itsik85** [ahaydon/Qlik-Cli#223]
Hi
I have a task that is supposed to start working at 3:00:00, in fact it came into action at 3:00:45 but only to the "queue" status, then it went to "Started" status at 03:13:12.
How can I get each of these times?

![image](https://github.com/ahaydon/Qlik-Cli-Windows/assets/13830285/00017618-3985-447b-b82c-bdc9e4060ef0)

**Comment by countnazgul** [comment]
You can get all these times with:

```powershell
Get-QlikTask -filter "id eq <TASK-ID-HERE>" -full | foreach-object {$_.operational.lastExecutionResult.details}
```

And check the `detailCreatedDate` property. These are the same details that QMC is reporting. (ignore that my times are the same. dont have an example for long running task atm)

![image](https://github.com/user-attachments/assets/5f521237-5f35-4d4c-bbe3-9a05fbd65913)

**Comment by itsik85** [comment]
Thank you!

I get the times in hh:mm format.
Why does it also appear with the seconds? How can I add them?


![image](https://github.com/user-attachments/assets/fd6ba112-8d94-48a2-98ab-3efa04ad35e4)

**Comment by countnazgul** [comment]
hmmm. not sure. feels like it might be due to you local settings? possible to try on another machine/server?

**Comment by itsik85** [comment]
I debugged the code and found the following line in the helper.ps1 file:
$object.$($prop.Name) = Get-Date -Format "yyyy/MM/dd HH:mm" $object.$($prop.Name)
I changed it to:
$object.$($prop.Name) = Get-Date -Format "yyyy/MM/dd HH:mm:ss" $object.$($prop.Name)

Now it works fine :)

**Comment by ahaydon** [comment]
Rather than modifying the module code you can use the `-raw` flag with the `Get-QlikTask` command, this flag prevents the output formatting in the module from applying and just outputs the raw values from the API.
