### ISSUE TITLE
Healthcheck API

### ISSUE THREAD

**Issue by SQLJames** [ahaydon/Qlik-Cli#27]
Is there a way we can have the qlik health check added to the Module? I was trying to get it to work but it keep failing.

http://help.qlik.com/en-US/sense-developer/September2017/Subsystems/EngineAPI/Content/GettingSystemInformation/HealthCheckStatus.htm

**Comment by ahaydon** [comment]
It's possible to use full URLs with the Invoke-QlikGet cmdlet so just pass the URL of the healthcheck API as the first parameter and it should return the information. If you're getting an error please post it here so we can help.
