### ISSUE TITLE
Unable to Replace the App in Stream upon Publishing

### ISSUE THREAD

**Issue by ahsyed** [ahaydon/Qlik-Cli#29]
Unable to Replace the App in Stream upon Publishing
The App is not able to get replaced upon Publishing the App. Please Add this functionality to the cmdlet.
Qlik-PublishApp cmdlet does not support the replacing app feature.

**Comment by ahaydon** [comment]
Please see the Switch-QlikApp cmdlet, this allows replacing an app. Though publishing and replacing are part of the same process in the hub this is not the case in the API so they are implemented as separate cmdlets.

**Comment by ahsyed** [comment]
Thanks ahaydon,
This has resolved the issue. Switch-QlikApp cmdlet came as a good workaround.
