### ISSUE TITLE
Unable to use due to lack of instructions

### ISSUE THREAD

**Issue by tuomassyvajarvi** [ahaydon/Qlik-Cli#31]
This might be excellent tool to manage Qlik Sense, but I'm unable to use it because there are not sufficient instructions available how script authenticates to Qlik Sense server. Given example about using certificates does not guide enough to get certificates working. Step by step intructions and examples of usage of function calls are necessary.

**Comment by SQLJames** [comment]
What part are you stuck at? These are the instructions I put together internally, if you have other problems with a specific step I am happy to help.

- Install instructions for Qlik-Cli
- Check to see if the powershell version is 4
- $PSVersionTable.PSVersion
- Check the execution policy level for your machine It should be set to RemoteSigned for this to work
- get-executionpolicy
- Copy the file to C:\Windows\System32\WindowsPowerShell\v1.0\Modules\Qlik-Cli
- Once copied run 
- Import-Module Qlik-Cli.psm1
- Confirm it is running by executing 
- get-help qlik
- Generate a certificate on the qlik sense server http://help.qlik.com/en-US/sense/1.1/Subsystems/ManagementConsole/Content/QMC_Resources_Certificates_Export.htm
- import that certificate to the local machine \ personal \ Certificates 
- gci cert:Localmachine\my | where { $_.friendlyname -eq 'QlikClient' } | connect-qlik {server name used in the certificate}

**Comment by knightriderX3** [comment]
Thanks @SQLJames for the start-up help!
Adding to  what @tuomassyvajarvi  is saying, there is no enough, sufficient and required help section to refer to on using the great commands Qlik-cli has got to offer... which makes it very difficult to use.

**Comment by nadiagomez** [comment]
Hi, by any chance is there any detailed manual about the configurations required for the certificates part?

**Comment by ahaydon** [comment]
There is now a wiki available.
