### ISSUE TITLE
This github and install-Module are very different versions

### ISSUE THREAD

**Issue by ChristofSchwarz** [ahaydon/Qlik-Cli#34]
There is a mismatch between the Qlik-Cli which I get when using "Install-Module" in PS 5.0 and when I download the Qlik-Cli.psm1 from this github. The first will install a 70kB big Qlik-Cli.psm1 under C:\Program Files\WindowsPowerShell\Modules\Qlik-Cli  whereas the latter is only 3kB in size and knows only 10 commands. 
![image](https://user-images.githubusercontent.com/15999058/33265233-ba2456aa-d368-11e7-81ec-f180a084bbf1.png)
How can I get the right Qlik-Cli.psm1 file if I am on Powershell 4.0 ? thanks

**Comment by ahaydon** [comment]
The PowerShell Gallery and GitHub releases are now automatically updated from the master branch so should all be consistent going forward.
