### ISSUE TITLE
Errors during execution in inforke RestMethod

### ISSUE THREAD

**Issue by hvdbunte** [ahaydon/Qlik-Cli#35]
Hello,

We have a script that is created by a Qlik consultant in the past to copy a template stream for a new client. We are using Qlik Sense November 2017 version with DLL’s from the current SDK version 13.3.0. 

But when I am running the script with the new dll's. I get these errors. I am not familiar with PowerShell so any help is appreciated.

nvoke-RestMethod : The underlying connection was closed: Could not establish trust relationship for the SSL/TLS secure channel.
At C:\windows\system32\windowspowershell\v1.0\Modules\qlik-cli\qlik-cli.psm1:77 char:15
+     $result = Invoke-RestMethod -Method $method -Uri $path @params -SessionVaria ...
+               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-RestMethod], WebException
    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeRestMethodCommand

And the other error is maybe because we don't run the latest version? I am not sure. 

New-QlikVirtualProxy : A parameter cannot be found that matches parameter name 'tags'.
At C:\windows\system32\windowspowershell\v1.0\Modules\qlik-cli\qlik-cl.psm1:582 char:410
+ ... ingServerNodes -tags $tags -verbose
+                    ~~~~~
    + CategoryInfo          : InvalidArgument: (:) [New-QlikVirtualProxy], ParameterBindingException
    + FullyQualifiedErrorId : NamedParameterNotFound,New-QlikVirtualProxy
 
Add-QlikProxy : Cannot bind argument to parameter 'VirtualProxyId' because it is an empty string.
At C:\windows\system32\windowspowershell\v1.0\Modules\qlik-cli\qlik-cli.psm1:587 char:68
+         Add-QlikProxy -ProxyId $(Get-QlikProxy).id -VirtualProxyId $virtualProxy ...
+                                                                    ~~~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [Add-QlikProxy], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationErrorEmptyStringNotAllowed,Add-QlikProxy
 
Method invocation failed because [Qlik.Engine.App] does not contain a method named 'GetProperties'.
At C:\windows\system32\windowspowershell\v1.0\Modules\qlik-cli\qlik-cli.psm1:342 char:9
+         $app.DoSave($app.GetProperties().FileName)
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : MethodNotFound
 
If you need more information please let me know. 

Thank you,

Hendri

**Comment by ahaydon** [comment]
The error "The underlying connection was closed: Could not establish trust relationship for the SSL/TLS secure channel." suggests that there is an issue with the certificate, maybe the hostname you are connecting to does not match the name on the certificate, or you have not installed the root certificate on the machine you are running the script from.

It looks like you may have upgraded from a very old version of this module, there were some big changes to the module that broke backwards compatibility and I suspect this is the issue. I suggest using the old module with the new SDK as that should resolve the issues with the cmdlets. However, the last error may be a change in the SDK, if this is the case it will prevent the script working with the latest versions of Sense and so the script code will require updating.
