### ISSUE TITLE
-customProperties syntax issue

### ISSUE THREAD

**Issue by theLaciBOY** [ahaydon/Qlik-Cli#36]
Hello,

I encountered issue when trying to create a new stream or data connection with custom property defined. Based in the help command   
New-QlikDataConnection [[-name] <string>] [[-connectionstring] <string>] [[-type] <string>] [-customProperties  <string[]>] [-tags <string[]>] [-username <string>] [-password <string>]  [<CommonParameters>]

I tried PS C:\windows\system32> New-QlikDataConnection -name CLI -connectionstring "c:\temp" -type folder -customProperties "CLI" but always ended with Bad Request
Invoke-RestMethod : The remote server returned an error: (400) Bad Request.

No matter what syntax I am using I am getting Bad Request when trying to define Custom Property via CLI.

Thanks for any comments here. The tool is awesome.
Kind Regards
Laci

**Comment by MiBrue** [comment]
Hi,

you should use 
-customProperties @("Propertyname=PropertyValue")

So, if your CustomProperty is named "AppName" and the choiceValues are
"Finance"
"Marketing"
"Support"

and you want to assign the Property with the value "Finance" than

-customProperties @("AppName=Finance")

regards
Michael

**Comment by theLaciBOY** [comment]
Thanks, working like a charm!

Keep Qliking
Cheers,
Laci

**Comment by knightriderX3** [comment]
Hi Micheal,

Can you please help with the syntax when we have to update(append) to the customProperty, say inlude Marketing also in the above example?


Best Regards,
K

**Comment by ZeidS** [comment]
Hi knightriderX3,

Try this 
-customProperties @("AppName=Finance","AppName=Marketing")

Best regards,
Zeid
