### ISSUE TITLE
Switch-QlikApp makes all sheets base sheets and removes destination sheets

### ISSUE THREAD

**Issue by alexometis** [ahaydon/Qlik-Cli#37]
When you run Switch-QlikApp the destination app (specified by -appId) gets all the sheets from the source app (specified by -id) - I think it also keeps its own non-Base sheets too from what I can tell.

This is of course most obvious when doing this from published app to published app where you can end up with hundreds of sheets appearing as Base when they were just "My Sheets" for multiple users before.

My use case is wanting to clone Production into a Sandbox environment for config testing (hence published to published) so I'm looping through a list of apps and doing this for each:
```
Switch-QlikApp -id (Get-QlikApp -filter "stream.name eq '$fromStream' and name eq '$app'").id 
-appId (Get-QlikApp -filter "stream.name eq '$toStream' and name eq '$app'").id
```

Doing publishing of a published app isn't possible in the QMC, you have to duplicate and republish. But the publishing behaviour in the QMC of this is that the destination app gets its base sheets replaced by the base sheets of the and keeps its non-base sheets (community & my sheets). Is there any way to replicate this behaviour with Qlik-Cli? I tried using Publish-QlikApp to start with but that doesn't appear to have a way to publish over an existing app and I assumed Switch-QlikApp is what I wanted... 

Do I have to copy, publish & delete to achieve this? Or will that just do the same thing?

**Comment by ahaydon** [comment]
The replace app API is intended for publish and replace as is available in QMC, so while the API allows a source app that is already published the results may be not what your're expecting. You can still use the Switch-QlikApp command but you should first copy the app so that it only has the base sheets.

**Comment by alexometis** [comment]
Thanks - I've done that now - Copy, Switch, Delete seems to work well.
I suppose I can pipe the Copy to the Switch (currently I'm just doing this by name) but there's no way to also pipe it to the Delete?

**Comment by alexometis** [comment]
From what I can tell, the passthrough pipes in the ID of the DESTINATION / published app (appId) not the SOURCe / unpublished app (Id) - that's the opposite of what I'd expect as you'd usually want to keep the app you're switching TO, not the one you're switching FROM... or have I misunderstood this command?

**Comment by ahaydon** [comment]
The command Switch-QlikApp -id $sourceid -appid $replaceid, outputs the $replaceid app
Whereas Switch-QlikApp -id $sourceid -appid $replaceid -Passthru, outputs the $sourceid app
All commands in Qlik-CLI will by default output whatever is returned by the API, the Passthru parameter allows the input object to be passed through to the output instead. Whatever is on the output can then be piped to the next command.

**Comment by alexometis** [comment]
Ah thanks - clarification much appreciated! 👍
