### ISSUE TITLE
Using & in variables in filters

### ISSUE THREAD

**Issue by alexometis** [ahaydon/Qlik-Cli#38]
Here's what I was trying to do:
```
$apps = 'This Extract','This & That Extract'

foreach ($app in $apps)
{	
	echo "Processing: $app"
	get-qlikapp -filter "stream.name eq 'Extract' and name eq '$app'" | copy-qlikapp -name "$app COPY"
}
```
The first app works fine, but any app with & in the name fails. 
If I run just:
```
get-qlikapp -filter "stream.name eq 'Extract' and name eq 'This & That Extract'" | copy-qlikapp -name "This & That Extract COPY"
```
it works fine, so it appears to be to do with how it's interpreting the string. 

I've tried escaping the & - `\&` or `` `& `` - in the variable and using `"` or `` ` `` around various things to no avail.

This may be my inexperience with PowerShell rather than an issue, but I couldn't find a workaround other than hard-coding the values. Interestingly Streams with & in them don't seem to cause the same issue.

**Comment by ahaydon** [comment]
The issue is that Copy-QlikApp is not encoding the name before sending the request to the API, it's fine for the filter as this is correctly encoded. As a workaround you should be able to use %26 in place of &.

**Comment by alexometis** [comment]
Thanks. I've tried it but to no avail:

```
$apps = 'This Extract','This %26 That Extract'

foreach ($app in $apps)
{	
	echo "Processing: $app"
	copy-qlikapp -id (get-qlikapp -filter "stream.name eq 'Extract' and name eq '$app'").id -name "$app COPY"
}
```

I've also tried double quotes when listing the app names. I'm not a PS expert so I'm not sure how it interprets that... but still I just get errors.

**Comment by ahaydon** [comment]
The issue is that the %26 is being passed to the filter and being encoded a second time, I have now updated the copy command to correctly encode the name so you can use & and it will be encoded automatically.

**Comment by alexometis** [comment]
Thanks - I'd renamed my apps to avoid this, so can't easily test now, but thanks for resolving.
