### ISSUE TITLE
switch -tags in Update-QlikUser fails

### ISSUE THREAD

**Issue by MiBrue** [ahaydon/Qlik-Cli#39]
HI,

using the CLI Command
   **Update-QlikUser**
with the switch "-tags" fails, regardles i'm using a Text or Text-Array as parameter.
It seems, that you wrap the result of a function call not as an array
I researched the code and fixed that problem.

In Script "**users.ps1**" Line **82** is

`$user.tags = GetTags $tags`

It should be
`      $user.tags = @(GetTags $tags)`

Thanks for your great Tool!!
Michael

**Comment by ahaydon** [comment]
Thank you for providing the fix, I have now updated this in the code.
