### ISSUE TITLE
Export multiple apps based on tag

### ISSUE THREAD

**Issue by theLaciBOY** [ahaydon/Qlik-Cli#40]
Hello,

Could you please help we with building a command which will export all apps containing specific tag e.g. DONE.
I have tried following attempts but without a luck.
Get-QlikApp -filter "tags eq 'DONE'" -raw | Export-QlikApp
Export-QlikApp -id $(Get-QlikApp -filter "tags eq DONE").id -filename "D:\Apps\"

Thanks in advance!
Laco

**Comment by levi-turner** [comment]
@theLaciBOY : 

`# This will export the apps with the tag of foo applied by the app ID
Get-QlikApp -filter "tags.name eq 'foo'" | Export-QlikApp
# This will export apps with the tag of foo applied with the app name as the filename
Get-QlikApp -filter "tags.name eq 'prod_ready'" | foreach {Export-QlikApp -id $_.id -filename "$($_.name).qvf"}`

**Comment by theLaciBOY** [comment]
Thanks Levi. doing exactly what requested!
Have a nice day!
Laco
