### ISSUE TITLE
Error (403) Forbidden.

### ISSUE THREAD

**Issue by nadiagomez** [ahaydon/Qlik-Cli#44]
Invoke-RestMethod : The remote server returned an error: (403) Forbidden.
At C:\Program Files\WindowsPowerShell\Modules\Qlik-Cli\functions\core.ps1:32 char:15
+     $result = Invoke-RestMethod -Method $method -Uri $path @params -WebSession $ ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-RestMethod], WebException
    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeRestMethodCommand

**Comment by ahaydon** [comment]
What is the command you are running that produces this error?
A 403 error suggests that you do not have the necessary permissions to perform the operation, what roles does your user have in Sense?

**Comment by nadiagomez** [comment]
I was trying to use the copy app method, my user is rootadmin.

**Comment by ahaydon** [comment]
Can you try running 'Connect-Qlik -Verbose' to confirm the authentication is succeeding. You should see a statement like "Using certificate ... and user ..." or "using Windows credentials". You could also try add -Verbose to the command you are running as this will provide more detailed output, pasting the verbose output here will help to determine the issue.

**Comment by nadiagomez** [comment]
Hi, the problem was we thought the script will take the user credentials provided into Connect-Qlik command line, but when the tool try to perform a "copy application" function it actually will take the user account that is running powershell, not the one provided into the parameters. We used "run as" option to execute the script with the appropriate user and we had no issues. Thanks.

**Comment by ahaydon** [comment]
Thanks for providing the resolution to your issue. I have removed the credential parameter for now as it is an issue with a base PS cmdlet so cannot be fixed within this module, hopefully this will get fixed and I can reintroduce the option.
