### ISSUE TITLE
Issue? Importing App & Replacing

### ISSUE THREAD

**Issue by pgrizz28** [ahaydon/Qlik-Cli#46]
Hi, Trying to set up a export/import & replace routine, which is working up to the replace.
As soon as I add the -replace switch and pass the GUID to replace hitting errors.
I've stepped through and see it failing at the Invoke, which I've stripped out and tested seperatly without joy.

Am I missing something or is this a bug?

**Invoke-QlikUpload -filename G:\Deployments\Everyone\Test_PG.qvf -path "/qrs/app/upload?name=Test_PG&replace=ec6526ea-8808-4b0d-84af-92b993a1dd45" -ContentType application/vnd.qlik.sense.app**

ERRORS WITH 

_Invoke-RestMethod : The remote server returned an error: (400) Bad Request.
At C:\windows\system32\windowspowershell\v1.0\Modules\Qlik-Cli\functions\core.ps1:32 char:15
+ ...   $result = Invoke-RestMethod -Method $method -Uri $path @params -Web ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-RestMethod], WebException
    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeRestMethodCommand_

**Comment by skillfarben** [comment]
Try using the cmdlet Import-QlikApp for uploading the QVF.
To replace an existing one you can use Switch-QlikApp

**Comment by skillfarben** [comment]
if you look at the function, it calls this method at the end
https://help.qlik.com/en-US/sense-developer/February2018/Subsystems/RepositoryServiceAPI/Content/RepositoryServiceAPI/RepositoryServiceAPI-App-Replace.htm
that means the app needs to be imported first, then published using Switch-QlikApp

In an older version of Qlik-CLI there was another method that imported and switched in one step, but that is not there any more. Also that is dangerous, as it is easy to make mistakes and lose work.

**Comment by pgrizz28** [comment]
ah... thanks very much for clarifying.
