### ISSUE TITLE
register-qliknode

### ISSUE THREAD

**Issue by clintcarr** [ahaydon/Qlik-Cli#48]
When registering or adding a new node with the -failovercandidate switch all services should default to install.

Failovers need all services.

In this version of Qlik-Cli failure to enable the services will only enable the repository.

**Comment by amien90** [comment]
don't you need to add the other switches too? So besides -failoverCandidate also add -engineEnabled -proxyEnabled -printingEnabled -schedulerEnabled.. not sure if you check -failoverCandidate, all the needed services are added automatically.
