### ISSUE TITLE
New-QlikRule's [int] fails on high action values

### ISSUE THREAD

**Issue by levi-turner** [ahaydon/Qlik-Cli#49]
Sample command: `New-QlikRule -Name Q-QMC-Administrators -resourceFilter * -actions 4294967295 -rule '(user.role="Administrator")' -rulecontext qmc -category Security -Verbose`

Response: 

> New-QlikRule : Cannot process argument transformation on parameter 'actions'. Cannot convert value "4294967295" to type "System.Int32". Error: "Value was either too large or too small for an Int32."
> At line:1 char:68
> + ... me Q-QMC-Administrators -resourceFilter * -actions 4294967295 -rule ' ...
> +                                                        ~~~~~~~~~~
>     + CategoryInfo          : InvalidData: (:) [New-QlikRule], ParameterBindingArgumentTransformationException
>     + FullyQualifiedErrorId : ParameterArgumentTransformationError,New-QlikRule

Fix: 
`[int]$actions,` > `[int64]$actions,`

Use case: Creating a pseudo RootAdmin role

`Get-QlikRule -filter "name eq 'RootAdmin'"`

> id             : 9a872869-8672-41da-9c6a-fc599e713aeb
> category       : Security
> type           : ReadOnly
> name           : RootAdmin
> rule           : user.roles = "RootAdmin"
> resourceFilter : *
> actions        : 4294967295
> comment        : Root admin should have full access rights
> disabled       : False
> privileges     :

**Comment by ahaydon** [comment]
this fix was included in v1.10
