### ISSUE TITLE
Filter options

### ISSUE THREAD

**Issue by theLaciBOY** [ahaydon/Qlik-Cli#50]
Hi,

Is there any chance to get list of all possible filters for Get-QlikApp function?
Stream name and app name are only ones that are working for me.
Get-QlikApp -filter "stream.name eq '$($appid.stream.name)' and name eq '$($appid.name)'"

I would like to filter for app name that is not published - any ideas how to achieve this?
Is it possible to use LastModified or empty stream in filter? If, so i would be grateful for any examples.

Thanks for any comments

**Comment by ucsi2ex5933jyb33** [comment]
Hi,

I don't have a list of filters, but to fine unpublished apps, try:

   get-qlikapp -filter "published eq False"
