### ISSUE TITLE
Replace in Import-QlikApp is not working

### ISSUE THREAD

**Issue by Tabris963** [ahaydon/Qlik-Cli#53]
Import-QlikApp still has the -replace option.
From Qlik's help, it seems that this option is not available since QS 2.2: [2.2 - App: Import app](https://help.qlik.com/en-US/sense-developer/2.2/Subsystems/RepositoryServiceAPI/Content/RepositoryServiceAPI/RepositoryServiceAPI-App-Import-App.htm)

Please remove it, in order to avoid confusion.

Many thanks,
Riccardo

**Comment by Nillth** [comment]
[Qlik Sense API's Nov 2018](https://help.qlik.com/en-US/sense-developer/November2018/APIs/repositoryserviceapi/index.html?page=220)

**Comment by ahaydon** [comment]
This issue was resolved some time ago.
