### ISSUE TITLE
How to update multiple values for a Custom Property?

### ISSUE THREAD

**Issue by knightriderX3** [ahaydon/Qlik-Cli#54]
Hi ,
-customProperties @("AppName=Finance")
Can you please help with the syntax when we have to update(append) to the customProperty, say inlude Marketing also as in the example referred in https://github.com/ahaydon/Qlik-Cli/issues/36?

Requirement - update the custom property that basically defines the streams a user can find in the hub. A user can see one or more streams.

Best Regards,
K

**Comment by gustafssone** [comment]
@knightriderX3 you can use  -customProperties @("PropertyA=ValueA"; "PropertyA=ValueB")

**Comment by knightriderX3** [comment]
Thanks!
That does, help, however, if there are already one ore more values set for that PropertyA, by running this command, they existing ones get replaced with this.

**Comment by gustafssone** [comment]
By reading the current ones, something like this (in order to update a custom property)

$allcurrentvalues = $(Get-QlikCustomProperty -filter "name eq 'PropertyA'").choicevalues

#notice the plus sign below
$allcurrentvalues += $ValueB
Update-QlikCustomProperty -id $(Get-QlikCustomProperty -filter "name eq 'PropertyA'").id -choiceValues $allcurrentvalues

**Comment by gustafssone** [comment]
Or on a user:

    #finds all previous values EXCEPT PropertyB
    $previousCPvalues = $(Get-QlikUser -filter "userid eq '$userid'" -full).customProperties | Where-Object { $_.definition.name -ne "PropertyB" }

    #loops them around and adds to our array, e.g. PropertyA, PropertyC
    #if we didn't do this, they would loose all previous custom properties
    foreach ($previousvalue in $previousCPvalues) {

        $prev = $previousvalue.definition.name + "=" + $previousvalue.value
        write-host the following previous custom properties was found:
        write-host $prev
        $stringcpperuser += $prev
        
    }
