### ISSUE TITLE
Export App without Data

### ISSUE THREAD

**Issue by analienx** [ahaydon/Qlik-Cli#59]
Since June 2018 there is a new parameter.
Would it be possible to add it there?
https://help.qlik.com/en-US/sense-developer/June2018/Subsystems/RepositoryServiceAPI/Content/RepositoryServiceAPI/RepositoryServiceAPI-App-Export-App-Two-Calls.htm

**Comment by levi-turner** [comment]
Hmm, I am not finding a method in native Qlik-CLI, but this runs clean for me locally on the server:
`Connect-Qlik
$id = Get-QlikApp -filter "name eq 'Operations Monitor'"
$Data = Get-Content C:\ProgramData\Qlik\Sense\Host.cfg
$FQDN = [System.Text.Encoding]::UTF8.GetString([System.Convert]::FromBase64String($($Data)))
$hdrs = @{}
$hdrs.Add("X-Qlik-Xrfkey","examplexrfkey123")
$hdrs.Add("X-Qlik-User", "UserDirectory=INTERNAL; UserId=sa_api")
$cert = Get-ChildItem -Path "Cert:\CurrentUser\My" | Where {$_.Subject -like '*QlikClient*'}
$body = '{}'
$downloadpath = Invoke-RestMethod -Uri "https://$($FQDN):4242/qrs/App/$($id.id)/export/6f9e5622-7306-4b00-9da2-15b132cf7984?xrfkey=examplexrfkey123&skipdata=true" -Method Post -Body $body -Headers $hdrs -ContentType 'application/json' -Certificate $cert
Invoke-RestMethod -Uri "https://$($FQDN):4242$($downloadpath.downloadPath)"   -Method Get -Headers $hdrs -ContentType 'application/json' -Certificate $cert |  Set-Content small.qvf -Encoding Ascii`

**Comment by Nillth** [comment]
Implemented in #67 functionality now available in current version
