### ISSUE TITLE
Connecting two environments 

### ISSUE THREAD

**Issue by epetra** [ahaydon/Qlik-Cli#6]
Hi! Great tool guys, although I have some difficulties trying to connect from one environment to another one. Both environments works fine by them self. Error Im getting:  

_Invoke-RestMethod : The underlying connection was closed: Could not establish trust relationship for the SSL/TLS
secure channel._

Any idea how to solve it? Or maybe you could explain more briefly about certificates? Thanks

**Comment by ahaydon** [comment]
The APIs are invoked over HTTPS so the security is the same as for accessing a secure website in a browser, you need to install the root certificate from the Sense server on the machine where you are running Qlik-Cli. The certificate can be exported from the Windows certificate store on the Sense server, it's in the trusted roots folder. You should not export the private key with the certificate.
