### ISSUE TITLE
Update Data Connection require connection string

### ISSUE THREAD

**Issue by gbjohnson7** [ahaydon/Qlik-Cli#65]
When trying to connection string username or password I noticed the connectionstring parameter was required.  I updated the powershell function to check if it's filled out or not. Below is an example.

if($ConnectionString){
        $qdc.connectionstring = $ConnectionString
    }

**Comment by Nillth** [comment]
Fixed in https://github.com/ahaydon/Qlik-Cli/pull/69
did not reference Issue #65 as I did not notice it... picked up on the issue implementing #66
