### ISSUE TITLE
Changing of App owner is not possible out of the box

### ISSUE THREAD

**Issue by theLaciBOY** [ahaydon/Qlik-Cli#68]
Hey,
Tool is not enabling change of app owner. At the moment it possible to change only app name, description, tag or custom properties. Is it possible to extent this functionality with enabling changing the owner, as well?

Actual Update-QlikApp function:

function Update-QlikApp {  [parameter(Mandatory=$true,ValueFromPipeline=$True,ValueFromPipelinebyPropertyName=$True,Position=0)]
    [string]$id,
    [string]$name,
    [string]$description,
    [string[]]$customProperties,
    [string[]]$tags

Any comments are appreciated, Thanks
BR, Laci

**Comment by Nillth** [comment]
fixed #60

**Comment by theLaciBOY** [comment]
Hi again after some time. Any chance of adding possibility to update the owner for Data Connections?
Thanks.

**Comment by ahaydon** [comment]
@theLaciBOY this has now been added to all commands and is available in the testing branch, it should be released soon and in the meantime feel free to try it out and submit issues if you find any.

**Comment by theLaciBOY** [comment]
Hi Adam, thanks for contacting me back. 
Well,  when creating the new data connection I am able to use -owner flag, all good here. This flag is unfortunately not possible to see when invoking Get-QlikDataConnection . Am I doing something wrong?

This are the parameters I can work with when using Get-QlikDataConnection
id               : ed045946-09b5-4838-9b40-83d04a7104fa
name             : #qliksense
connectionstring : https://docs.google.com/spreadsheets/someurl
type             : internet
engineObjectId   : ed045946-09b5-4838-9b40-83d04a7104fa
username         : 
logOn            : 0
architecture     : 0
privileges       : 

Thanks for any comments.

**Comment by ahaydon** [comment]
The Get commands output condensed objects by default, if you get an item directly using its ID or use the -full flag you will get the full items with all properties.

**Comment by theLaciBOY** [comment]
Thanks Adam, I forgot about  -full flag which solved my issue. Thanks for introducing this new functionality. Tool is very useful in enterprise environments!
