### ISSUE TITLE
Update-QlikUser applies wrong character encoding

### ISSUE THREAD

**Issue by gustafssone** [ahaydon/Qlik-Cli#77]
When using the following script:

$userid= 'tiilag'
$currentpropername = "Ström Tina"
Update-QlikUser -id $(Get-QlikUser -filter "userid eq '$userid'" -full).id -name $currentpropername 

The users name switches from "Ström Tina" to "Str�m Tina". It seems to be a problem with character encoding. 
Can we force the charset for the Invoke-RestMethod ?
I've tried to convert it by [System.Text.Encoding]::UTF8.GetBytes($currentpropername) and using New-Object -typename System.Text.UTF8Encoding but it doesn't seem to work. Most other online solutions are not built around a library like Qlik-Cli, meaning perhaps we can enforce it within the script?

**Comment by amien90** [comment]
i had the same issue and Adam gave this solution which worked:

I've found the problem, the content type in Qlik-Cli is set to "application/json" and needs to be changed to "application/json; charset=utf-8"

**Comment by gustafssone** [comment]
I see! Do I set this in the script in general, or directly in for instance "Update-QlikUser"? @amien90

**Comment by amien90** [comment]
i changed it in this file : Qlik-Cli.psm1

and then imported the library again

**Comment by gustafssone** [comment]
Seems to work, yay!

**Comment by ahaydon** [comment]
resolved
