### ISSUE TITLE
Unable to run Qlik- cli qliksense CMDlet for powershell

### ISSUE THREAD

**Issue by chinyamurthy** [ahaydon/Qlik-Cli#81]
Hi,

We are using QLIk-Cli.psm1 to start the task remotely.

I am able to run the powershell script through application service ID, but if same script when I try to run with our another alternate service ID( used only for remote execution) it doesn't work.

I tried providing Admin access to Alternate Service ID, it doesn't work.

 

Below is the error::\CorpData\UserFiles\QlikSenseBatch\Job\JHDH_Composable_Extract_test.ps1

********************************************************************************************************************

Invoke-RestMethod : The remote server returned an error: (403) Forbidden.

At E:\CorpData\UserFiles\QlikSenseBatch\QlikCliTaskTrigger\Qlik-Cli.psm1:77 char:15

+ ... $result = Invoke-RestMethod -Method $method -Uri $path @params -Ses ...

+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

+ CategoryInfo : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-RestMethod], WebException

+ FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeRestMethodCommand

 

Invoke-RestMethod : The remote server returned an error: (403) Forbidden.

At E:\CorpData\UserFiles\QlikSenseBatch\QlikCliTaskTrigger\Qlik-Cli.psm1:80 char:15

+ ... $result = Invoke-RestMethod -Method $method -Uri $path @params -Web ...

+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

+ CategoryInfo : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-RestMethod], WebException

+ FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeRestMethodCommand

 

Get-Member : You must specify an object for the Get-Member cmdlet.

At E:\CorpData\UserFiles\QlikSenseBatch\QlikCliTaskTrigger\Qlik-Cli.psm1:116 char:30

+ ... $Script:enums = $enums | Get-Member -MemberType NoteProperty | forea ...

+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

+ CategoryInfo : CloseError: (Smiley Happy [Get-Member], InvalidOperationException

+ FullyQualifiedErrorId : NoObjectInGetMember,Microsoft.PowerShell.Commands.GetMemberCommand

 

Invoke-RestMethod : The remote server returned an error: (403) Forbidden.

At E:\CorpData\UserFiles\QlikSenseBatch\QlikCliTaskTrigger\Qlik-Cli.psm1:80 char:15

+ ... $result = Invoke-RestMethod -Method $method -Uri $path @params -Web ...

+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

+ CategoryInfo : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-RestMethod], WebException

+ FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeRestMethodCommand

 

Invoke-RestMethod : The remote server returned an error: (403) Forbidden.

At E:\CorpData\UserFiles\QlikSenseBatch\QlikCliTaskTrigger\Qlik-Cli.psm1:80 char:15

+ ... $result = Invoke-RestMethod -Method $method -Uri $path @params -Web ...

+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

+ CategoryInfo : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-RestMethod], WebException

+ FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeRestMethodCommand

 

Invoke-RestMethod : The remote server returned an error: (403) Forbidden.

At E:\CorpData\UserFiles\QlikSenseBatch\QlikCliTaskTrigger\Qlik-Cli.psm1:80 char:15

+ ... $result = Invoke-RestMethod -Method $method -Uri $path @params -Web ...

+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

+ CategoryInfo : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-RestMethod], WebException

+ FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeRestMethodCommand

 

Get-Member : You must specify an object for the Get-Member cmdlet.

At E:\CorpData\UserFiles\QlikSenseBatch\QlikCliTaskTrigger\Qlik-Cli.psm1:116 char:30

+ ... $Script:enums = $enums | Get-Member -MemberType NoteProperty | forea ...

+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

+ CategoryInfo : CloseError: (Smiley Happy [Get-Member], InvalidOperationException

+ FullyQualifiedErrorId : NoObjectInGetMember,Microsoft.PowerShell.Commands.GetMemberCommand

 

Invoke-RestMethod : The remote server returned an error: (403) Forbidden.

At E:\CorpData\UserFiles\QlikSenseBatch\QlikCliTaskTrigger\Qlik-Cli.psm1:80 char:15

+ ... $result = Invoke-RestMethod -Method $method -Uri $path @params -Web ...

+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

+ CategoryInfo : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-RestMethod], WebException

+ FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeRestMethodCommand

************************************************************************************************************

I tried following adding execution policy, it did not work.

Set-ExecutionPolicy RemoteSigned

 

It will be great help if someone can advice on how to fix this.

 

Script:

 

import-module "E:\CorpData\UserFiles\QlikSenseBatch\QlikCliTaskTrigger\Qlik-Cli.psm1"

connect-qlik Servername -username Internal\sa_scheduler

start-qliktask "Task Name"

 

Regards,

bharath

**Comment by Nillth** [comment]
not sure what "Job\JHDH_Composable_Extract_test.ps1" is as it is not part of Qlik-Cli

judging from the errors you have list above 
Invoke-RestMethod : The remote server returned an error: (403) Forbidden.
At E:\CorpData\UserFiles\QlikSenseBatch\QlikCliTaskTrigger\Qlik-Cli.psm1:80 char:15

it appears that the account you are using to run the Qlik-Cli's "Connect-Qlik" command does not have permissions to authenticate against the QRS API. 
please review the following
https://github.com/ahaydon/Qlik-Cli/wiki/Establishing-a-connection
