### ISSUE TITLE
New licenses - professional and analyzer

### ISSUE THREAD

**Issue by gustafssone** [ahaydon/Qlik-Cli#84]
I noticed that there is no support for Professional and Analyzer licenses. It needs to be added in the resources/license.ps1 file.
From what I can see, the following is missing (please verify):

function Get-QlikAnalyzerAccess {
  [CmdletBinding()]
  param (
    [parameter(Position=0)]
    [string]$id,
    [string]$filter,
    [switch]$full,
    [switch]$raw
  )

  PROCESS {
    $path = "/qrs/license/analyzerAccessType"
    If( $id ) { $path += "/$id" }
    If( $full ) { $path += "/full" }
    If( $raw ) { $rawOutput = $true }
    return Invoke-QlikGet $path $filter
  }
}

function Get-ProfessionalAccessType {
  [CmdletBinding()]
  param (
    [parameter(Position=0)]
    [string]$id,
    [string]$filter,
    [switch]$full,
    [switch]$raw
  )

  PROCESS {
    $path = "/qrs/license/professionalaccesstype"
    If( $id ) { $path += "/$id" }
    If( $full ) { $path += "/full" }
    If( $raw ) { $rawOutput = $true }
    return Invoke-QlikGet $path $filter
  }
}

function New-QlikProfessionalAccessGroup {
  [CmdletBinding()]
  param (
    [string]$name
  )

  PROCESS {
    $json = (@{
      name=$name
    } | ConvertTo-Json -Compress -Depth 10)

    return Invoke-QlikPost "/qrs/License/ProfessionalAccessGroup" $json
  }
}

function Remove-QlikProfessionalAccessType {
  [CmdletBinding()]
  param (
    [parameter(Position=0,ValueFromPipelinebyPropertyName=$true)]
    [string]$id
  )
  PROCESS {
    return Invoke-QlikDelete -path "/qrs/license/professionalaccesstype/$id"
  }
}

**Comment by ahaydon** [comment]
These cmdlets have been added in #86 
Thanks for contributing.
