### ISSUE TITLE
Get-ProfessionalAccessType not working to use

### ISSUE THREAD

**Issue by gustafssone** [ahaydon/Qlik-Cli#87]
Hi!

I'm trying out the new version 1.16.0, where Get-QlikAnalyzerAccess is present (and is working).
I can't seem to find or use Get-ProfessionalAccessType though. 

I can see that the function is present in the file C:\Program Files\WindowsPowerShell\Modules\Qlik-Cli\1.16.0\resources\license.ps1, but it doesn't get imported, is not usable, and not visible through get-help.

![image](https://user-images.githubusercontent.com/25029962/63152762-e4aa0900-c00c-11e9-86a1-93e7f78002d0.png)

Any ideas?

Also, Remove-QlikAnalyzerAccessType is missing.

I know I filed the last bug :)
Is the naming here correct though, accessing the API ...accesstype, but he function for analyzer is called just "access"?

**Comment by ahaydon** [comment]
It looks like the cmdlet for Professional access type is named incorrectly so that's why it is not exported, and there is some inconsistency in the naming so this will also need to be fixed.

**Comment by ahaydon** [comment]
The cmdlet has now been correctly named as Get-QlikProfessionalAccessType and the Remove-QlikAnalyzerAccessType has been added in #91

**Comment by ShalakaKshirsagar** [comment]
Hello @ahaydon ,

Greetings !

I am trying to use 
Get-QlikAnalyzerAccessType -filter "lastUsed lt '$inactive'" -full  | Remove-QlikAnalyzerAccessType

however its not working.  What are the parameters to be passed to Get-QlikAnalyzerAccessType and 
Remove-QlikAnalyzerAccessType

**Comment by ahaydon** [comment]
Hi @ShalakaKshirsagar,

As the original issue has been resolved please open a new issue if the command is not working correctly. Please also include details of the error message or an explanation of what is actually happening. You command looks correct as long as the $inactive variable contains a correctly formatted date.
