### ISSUE TITLE
Get-QlikUserAccessType not giving any output

### ISSUE THREAD

**Issue by itibook** [ahaydon/Qlik-Cli#88]
Hello,

running the latest version and when I run Get-QlikUserAccessType I don't get any output. Did I miss something or this a bug?

**Comment by ahaydon** [comment]
Do you have a token based license and rights to view user access types, e.g. RootAdmin?

**Comment by initit** [comment]
I checked Get_QlikUSerAccessType in our environment and it works fine! Token Based License and i run local with account which has RootAdmin role.

**Comment by itibook** [comment]
@initit 

do you have a sample script? Maybe I am probably doing something really silly... yes running RootAdmin user. 

When I run 

`Get-QlikUser -filter "userid eq 'test@test'" `

I get the right output 

When I run 

` Get-QlikUserAccessType -filter "id eq 'id-from-license-panel-tab-in-qmc'"`

I get a 400 error

_**Invoke-RestMethod : The remote server returned an error: (400) Bad Request.**_

thanks in advance with whatever help you can provide.

**Comment by initit** [comment]
I confirm, that using filter this will result in an (400) Bad Request error. 
Seems that it is a QRS Problem and not based on Qlik-Cli.
I would try to get more information about that very strange behavior.
For the moment, you could try to catch all data (/full) and than loop through till you find the one your are looking for ...

**Comment by ahaydon** [comment]
You don't need single quotes around an ID, try using the following instead.

`Get-QlikUserAccessType -filter "id eq id-from-license-panel-tab-in-qmc"`

Also, you don't need to use filters when you know the ID, just provide it after the command.

`Get-QlikUserAccessType id-from-license-panel-tab-in-qmc`

**Comment by itibook** [comment]
@ahaydon thanks for the tips, but not getting any luck...

when I try the first option you proposed I don't get any output, the second one gives me a 404 error.

I am on QlikSense Server June 2019 Edition

**Comment by initit** [comment]
Hi @itibook,
did some more testing.
As @ahaydon  suggested, you have to pay attention about formatting the filter.

These commands runs with success:

Get-QlikUserAccessType  -filter "modifiedbyusername so 'test'" -full
Get-QlikUserAccessType  -filter "user.id eq ab5fce20-c5f5-4cf4-b4f3-1d80b2ac640b" -full
Get-QlikUserAccessType -filter "id eq e4709a78-9b24-4ba5-be05-8246ee65d53c" -full

So, searching the id (GUID) do not use '
Searching a text (like username) use '
Also, it seem that you could filter an id only with the "eq" operator
filtering textes, you could use "sw", "so" "eq" ...

My Server is Qlik Sense **November 2018 Patch 1** (12.44.2)

**Comment by itibook** [comment]
Hi @initit,

Some more digging... :-)

running a filter on userid for the QlikUser command WITHOUT single quotes gives me a 400 error

`$user = Get-QlikUser -filter "userid eq user1" -full`

running a filter on userid for QlikUser command WITH single quotes gives me the good result

`$user = Get-QlikUser -filter "userid eq 'user1'" -full`

when running a similar request on the Get-QlikUserAccessType as you suggested I get a 400 error WITH single quotes, and no data WITHOUT single quotes...

Not quite sure anymore what I could check now... :confused:

**Comment by ahaydon** [comment]
You use need to wrap strings in single quotes, but UUIDs are not strings and should not have single quotes.

The userId property of a user is a string and so requires single quotes, but id is a UUID so does not.

With the Get-QlikUserAccessType you are querying user access passes which have a user property containing the user object associated with the access pass, so id is a UUID, user.id is also a UUID, but user.userId is a string.

If you're getting no data and no error then the request is succeeding and returning all the objects that you have access to.

How are you authenticating?

If you are providing the username parameter to the connect command and expecting to be authenticated as that user then you need to be supplying a certificate to authenticate, otherwise you will be authenticated as the account running the powershell console.

**Comment by itibook** [comment]
@ahaydon ah ok thanks... 

the authentication part was not clear... must be that then thanks again for all the tips and help in troubleshooting, very much appreciated!

**Comment by ahaydon** [comment]
> @ahaydon ah ok thanks...
> 
> the authentication part was not clear... must be that then thanks again for all the tips and help in troubleshooting, very much appreciated!

I completely agree, it should not be possible to provide an invalid parameter, I will fix this.

**Comment by itibook** [comment]
@ahaydon 

btw, is there a way to check what user is being authenticated via the PS script? 

because with the Connect command I am using, I can upload and publish apps. So quite curious to know what user I am being authenticated if it's not the one I supplied via the Connect command...

**Comment by ahaydon** [comment]
@itibook you can use the -Verbose switch with the connect command, it will display either the username or that it is using default credentials which means logged on user.
