### ISSUE TITLE
Invoke-QlikPut 400 bad request

### ISSUE THREAD

**Issue by GustavGager** [ahaydon/Qlik-Cli#90]
Im trying to create a script to replace the SSL-cert Thumbprint of QS. I can get it working using postman by doing a GET to the proxy and then modifiying the sslBrowserCertificateThumbprint property and then run a new request to the same URI using the Put Method.

But when i try to get it working with Qlik-CLI, i get a 400 - bad request.
Here is my script so far:

Connect-Qlik
$proxies = Invoke-QlikGet -path "/qrs/proxyservice";
$path = "/qrs/proxyservice/" + $proxies.id;
$proxy = Invoke-QlikGet -path $path;
#$proxy.settings.sslBrowserCertificateThumbprint = $Thumbprint_in_certstore;
Invoke-QlikPut -path $path -body $proxy;

The error i get is:
Invoke-RestMethod : The remote server returned an error: (400) Bad Request.
At C:\Program Files\WindowsPowerShell\Modules\Qlik-Cli\1.16.0\functions\core.ps1:36 char:17
+ ...   $result = Invoke-RestMethod -Method $method -Uri $path @params -Web ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-RestMethod], WebException
    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeRestMethodCommand

**Comment by GustavGager** [comment]
For anyone reading this. This is NOT an issue with Qlik CLI. The error was becuase i did not convert $proxy object back to JSON. 
Using this, it works fine!
Invoke-QlikPut -path $path -body ($Proxy | ConvertTo-Json -Compress -Depth 100);

**Comment by Justformoment** [comment]
Hello Team,

I have the same error when I use Invoke-QlikPut, I want to modify nextExecution.
**Here is my script:**

 $body = @{
id = "65c9889a-a86d-46a2-b983-3aef56f37e36";
createdDate = "2019/11/18 07:51";
modifiedDate = "2019/11/18 07:51";
modifiedByUserName = "INTERNAL\sa_repository";
lastEventDate = "1752/12/31 19:00";
nextExecution = "2019/11/19 19:00";
timesTriggered = 0;
privileges =$null;
schemaPath = "SchemaEventOperational"
}
Invoke-QlikPut -path '/qrs/schemaeventoperational/65c9889a-a86d-46a2-b983-3aef56f37e36' -body ($body | ConvertTo-Json)

**Here is the error:**
Invoke-RestMethod : The remote server returned an error: (400) Bad Request.
At C:\Program Files\WindowsPowerShell\Modules\Qlik-Cli\functions\core.ps1:40 char:15
+ ...   $result = Invoke-RestMethod -Method $method -Uri $path @params -Web ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-RestMethod], WebException
    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeRestMethodCommand

**Comment by Nillth** [comment]
Note: If you have more than one Proxy returned by the first Invoke-QlikGet
> `$proxies = Invoke-QlikGet -path "/qrs/proxyservice";`
 you will have issues with the $path variable set on the next line
> `$path = "/qrs/proxyservice/" + $proxies.id;`
you may want to filter the returned $proxies to make sure you are setting the SSL Thumbprint on the correct proxy service

**Comment by GustavGager** [comment]
Im still having issues with this,
It works on our internal testserver but i cannot get it working on some of our customers servers.
The only difference i can find that might be relevant is that we use Forms authentication. But that is a virtual proxy and should not be relavant to this. 
All theese servers are single-node deployments and therefor only have one proxy.

I have tried reading the entire JSON object from the API with a qlik-get and stored it in a varible and then use qlik-put to update it with the same value, but it still doesnt work. Do i need to reformat the text in any other way? Can it be related to date formats and stuff like that??

**Comment by ahaydon** [comment]
the responses are reformatted for readability, this causes a problem when sending the data back to the API. Try using `Get-QlikProxy -raw $proxies.id`, the -raw switch prevents the response being formatted. You can also switch off response formatting by setting `$rawOutput = $true`.
