### ISSUE TITLE
Qlik-CLI and Qlik anlytic platform issues

### ISSUE THREAD

**Issue by michasiuk** [ahaydon/Qlik-Cli#96]
Has anyone tried to used the Qlik-CLI with the Qlik analytics platform or QAP. I have been tasked with doing some automation using PowerShell and the Qlik-CLI to Automate Reload Tasks to be managed with CA-AutoSys. Everything works fine with Qlik Sense but we are having issues with it on the QAP just wondering if the API's are different in QAP vs Qlik Sense mainly because I cannot get the cmdlts to respond on the QAP Server.

**Comment by ahaydon** [comment]
The APIs in QAP are exactly the same as Qlik Sense Enterprise, it's the same product with a different license that disables the hub. Please provide more details of your issue and maybe we can help.

**Comment by Nillth** [comment]
Stale
