### ISSUE TITLE
Update-QlikDataConnecion -owner format 

### ISSUE THREAD

**Issue by theLaciBOY** [ahaydon/Qlik-Cli#97]
Hello again.  after a while I'm coming back tot his topic. I am not able to update owner of a Data Connection. I am executing below command where data connection is updated except of the owner which remains the same
Update-QlikDataConnection -id $destdataconn.id -connectionstring $dataconn.connectionstring -owner $dataconn.owner

$dataconn.owner consist of
id : f71e376e-f2d4-4a2d-acc6-37bff42630e0
userId : id
userDirectory : domain
name : name
privileges :

Could you please assist in which format do i need to provide owner value ?
Thanks in advance.

**Comment by Nillth** [comment]
if the Update command is not working, then you can hit the api directly with Invoke-QlikPut.
I will look at the update-qlikdataconnection and see if I can fix it.

For the moment however, this should work. 

The Owner needs to be a Condensed User object.
The easiest way to get that is to do a Get-QlikUser and get the condensed user object... e.g. below.
Then pass that back to Invoke Put.

```
$UserID = "Nillth"
$UserDirectory = "Lab"
$OwnerObject = Get-QlikUser -filter "userid eq '$($UserID)' and userdirectory eq '$($UserDirectory)'"

$body = @{
id = $destdataconn.id
owner = $OwnerObject 
connectionstring $dataconn.connectionstring
modifiedDate= $(get-date -Format "yyyy-MM-dd HH:mm").ToString()
}
Invoke-QlikPut "/qrs/dataconnection/$($body.id)" -body $($body|ConvertTo-Json)
```

**Comment by Nillth** [comment]
Stale

**Comment by theLaciBOY** [comment]
> if the Update command is not working, then you can hit the api directly with Invoke-QlikPut.
> I will look at the update-qlikdataconnection and see if I can fix it.
> 
> For the moment however, this should work.
> 
> The Owner needs to be a Condensed User object.
> The easiest way to get that is to do a Get-QlikUser and get the condensed user object... e.g. below.
> Then pass that back to Invoke Put.
> 
> ```
> $UserID = "Nillth"
> $UserDirectory = "Lab"
> $OwnerObject = Get-QlikUser -filter "userid eq '$($UserID)' and userdirectory eq '$($UserDirectory)'"
> 
> $body = @{
> id = $destdataconn.id
> owner = $OwnerObject 
> connectionstring $dataconn.connectionstring
> modifiedDate= $(get-date -Format "yyyy-MM-dd HH:mm").ToString()
> }
> Invoke-QlikPut "/qrs/dataconnection/$($body.id)" -body $($body|ConvertTo-Json)
> ```

Apologies, i forgot to reply. Your hint helped. Thanks.
