### ISSUE TITLE
Connect-Qlik fails without a certificate in the pipe

### ISSUE THREAD

**Issue by vbakke** [ahaydon/Qlik-Cli#98]
Not sure if this was intentional or not. But after v 1.17.0 I can no longer run `Connect-Qlik`. I need to use the long version:
```powershell
Get-ChildItem cert:CurrentUser\My | Where-Object { $_.FriendlyName -eq 'QlikClient' } | Connect-Qlik sense-central
```

The simple `Connect-Qlik` command gives me this message:
```
PS C:\Windows\system32> Connect-Qlik
cmdlet Connect-Qlik at command pipeline position 1
Supply values for the following parameters:
Certificate: 
```

I could be `Certificate` parameter that has become Mandatory, see the Line 25 in Qlik-Cli.psm1:

https://github.com/ahaydon/Qlik-Cli/commit/0d1a8a7f48b15416b57888418ae9c0b0a3ad2890#diff-71f978293d65f1a6c0d6c2853246e084

That being said. I really appreciate the Qlik-Cli module,and that your keep updating it as Qlik Sense develops!  Thank you!  :)

**Comment by ahaydon** [comment]
This should now be resolved, the default parameter set has been changed from Certificate to Default. This allows for the command to automatically determine the best connection options as before, while preventing the username parameter being used with Windows authentication as this is an invalid combination.

This change is not yet released to the PowerShell Gallery but is available in the master branch.
