### ISSUE TITLE
Update-QlikExtension - update customproperties

### ISSUE THREAD

**Issue by diago132** [ahaydon/Qlik-Cli#99]
I have tested the function Update-QlikExtension which didn't run and when I open the powershell extension.ps1, I saw that the customproperties update was on $app instead of $ext (bad copy/paste) : the good code is
if ($PSBoundParameters.ContainsKey("customProperties")) { $ext.customProperties = @(GetCustomProperties $customProperties) }

BR
diago132

**Comment by ahaydon** [comment]
Thank you for reporting this issue, it has now been fixed.
